### ISSUE TITLE
undefined error

### ISSUE THREAD

**Issue by tung256** [mumblebaj/MMM-WOTD#10]
i installed. rebooted my rpi3.
now i get this error. any idea how to resolve?
![image](https://github.com/user-attachments/assets/270f9ba0-7edd-48a4-80f8-cb1c195c426d)

**Comment by mumblebaj** [comment]
Hi. Can you check for any errors in the logs or terminal? Are you on the latest version of the module? In the module directory you can do a `git status` to check if you on the latest version. You mentioned updating your mirror. Which version are you on now? v2.29 is not compatible with Rpi3.

**Comment by mumblebaj** [comment]
Ok, I just a test and it seems like the site is a problem. I will investigate a bit further.

**Comment by mumblebaj** [comment]
Website changed. Seems like the change the site more frequently. It takes time to get the changes. I will have a look at it in the next few days.

**Comment by RockNRollGeek** [comment]
any update on this? fresh install with the same issue. was using the other wotd module but liked that this one didn't have the examples, but might need to go back to the old one.

**Comment by mumblebaj** [comment]
Hi. I am working on it. Sites have changed and keeps changing and I have a bit of a broken arm. Will advise once updates

**Comment by mumblebaj** [comment]
Hi @RockNRollGeek  and @tung256 . The sites I collect the data from has changed a bit too much and the tags keep getting updated daily. It is near impossible to get it to work. I will have to find a new source/s. Until then I am unable to get the module working properly.

**Comment by mumblebaj** [comment]
@RockNRollGeek  and @tung256 I have found a way. It will take a bit of rewriting. I will try my best with my arm issue. Maybe the next few days.

**Comment by tung256** [comment]
no rush my friend.  rest well.

**Comment by mumblebaj** [comment]
Hi @RockNRollGeek  and @tung256 .
Module has been updated. Please do a `git pull && npm install` in the module folder.
