### ISSUE TITLE
Stuck on Loading

### ISSUE THREAD

**Issue by hrjmsh** [mumblebaj/MMM-WOTD#4]
Installed today. It is stuck on Loading. Reduced the delay interval down to 120 seconds but still no luck,

**Comment by mumblebaj** [comment]
Did you run `npm install` in the module folder? Are there any errors in the developer console? (shift_ctrl_i)

**Comment by hrjmsh** [comment]
I did run the npm install. No errors were found in the developer console.

**Comment by mumblebaj** [comment]
which language have you selected to use?  Can you send me your config?

**Comment by mumblebaj** [comment]
I have changed the source of the Spanish words to a more stable source.  Please do a git pull again. Spanish should work and be more stable going forward.

**Comment by mumblebaj** [comment]
@hrjmsh Can you please advise if this has worked for you and if the issue can be closed? 
Thanks

**Comment by hrjmsh** [comment]
Yes, it has worked. Thank you,
